/* Replace with your SQL commands */

INSERT INTO questions (question, answer) VALUES 
    ('Who founded FBLA?', 'Hamden L. Forkner'),
    ('What year was the first state chapter chartered?', '1947'),
    ('In what city was the first FBLA chapter chartered?', 'Johnson City, Tennessee'),
    ('What year was the first local chapter chartered?', '1942'),
    ('What group purchased the land for the FBLA-PBL National Center?', 'Conrad N. Hilton Foundation'),
    ('What year was Phi Beta Lambda created?', '1958'),
    ('Who was the first executive director of FBLA-PBL?', 'Dr. Edward Miller'),
    ('Where is the National FBLA-PBL Center located?', 'Reston, Virginia'),
    ('When was the Professional Division created?', '1989'),
    ('What is the national policy making body for FBLA-PBL, Inc.?', 'National Board of Directors'),
    ('What is the national publication for FBLA and FBLA-ML members?', 'Tomorrow''s Business Leader'),
    ('What is the national publication for FBLA and FBLA-ML advisers?', 'Hotline'),
    ('What is the informational publication that each local chapter receives?', 'Chapter Management Handbook'),
    ('What is the national program that encourages chapters to team up to leverage their potential for success?', 'Connecting Chapters'),
    ('What does CSA stand for?', 'Community Service Awards'),
    ('What does BAA stand for?', 'Business Achievement Awards'),
    ('What is the national program that recognizes local chapters who maintain or increase their membership over the previous year''s total?', 'Membership Achievement Award'),
    ('Which officer presides over and conducts meetings according to Parliamentary Procedure?', 'President'),
    ('What is the written action plan called?', 'Program of Work'),
    ('Who is the president and CEO of FBLA-PBL?', 'Alexander T. Graham'),
    ('In the officer installation ceremony, what color candle represents the reporter?', 'Violet'),
    ('In the officer installation ceremony, what color candle represents the entire chapter?', 'White'),
    ('In the officer installation ceremony, what color candle represents the president?', 'Red'),
    ('In the officer installation ceremony, what color candle represents the vice president?', 'Orange'),
    ('In the officer installation ceremony, what color candle represents the secretary?', 'Yello'),
    ('In the officer installation ceremony, what color candle represents the treasurer?', 'Light Blue'),
    ('In the officer installation ceremony, what color candle represents the historian?', 'Green'),
    ('In the officer installation ceremony, what color candle represents the parliamentarian?', 'Gray'),
    ('Who is the Staff Accountant of FBLA-PBL?', 'Mary Ait'),
    ('Who is the Sponsors & Partners Coordinator of FBLA-PBL?', 'Ashlee Woodson'),
    ('Who is the Customer Service Associate of FBLA-PBL?', 'Colin Murphy'),
    ('Who is the Membership Director of FBLA-PBL?', 'Lisa Smothers'),
    ('Who is the Conference Manager of FBLA-PBL?', 'Robert Smothers'),
    ('Who is the Education Director of FBLA-PBL?', 'Kelly Scholl'),
    ('Who is the Education Associate of FBLA-PBL?', 'Aric Mills'),
    ('Who is the Director of Communications & Marketing of FBLA-PBL?', 'Gabrielle Gallagher'),
    ('Who is the Digital Marketing Coordinator of FBLA-PBL?', 'Lauren McMahon'),
    ('Who is the FBLA National President?', 'Drew Lojewski'),
    ('Who is the PBL National President?', 'Gabrielle Murphy'),
    ('Who is the Professional Division National President?', 'Alan Rzepkowski'),
    ('Who is the FBLA National Secretary?', 'Hana Le'),
    ('Who is the FBLA National Treasurer?', 'John Lee'),
    ('Who is the FBLA National Parliamentarian?', 'Kianna Bolante'),
    ('Who is the FBLA National Eastern Region Vice President?', 'Andrew Fox'),
    ('Who is the FBLA National Western Region Vice Presdient?', 'Sachin Sundar'),
    ('Who is the FBLA National Southern Region Vice President?', 'Maria Manabat'),
    ('Who is the FBLA National North Central Region Vice President?', 'Rhea Mehta'),
    ('Who is the FBLA National Mountain Plains Region Vice President?', 'Kaylee Reese'),
    ('What year was the FBLA-ML division established at the national level?', '1994'),
    ('What state became the first state chapter?', 'Iowa');