/* Replace with your SQL commands */

INSERT INTO questions (question, answer, comparison) VALUES 
    ('Who founded FBLA?', 'Hamden L. Forkner', 'hamden l forkner'),
    ('What year was the first state chapter chartered?', '1947', '1947'),
    ('In what city was the first FBLA chapter chartered?', 'Johnson City, Tennessee', 'johnson city tennessee'),
    ('What year was the first local chapter chartered?', '1942', '1942'),
    ('What group purchased the land for the FBLA-PBL National Center?', 'Conrad N. Hilton Foundation', 'hilton foundation'),
    ('What year was Phi Beta Lambda created?', '1958', '1958'),
    ('Who was the first executive director of FBLA-PBL?', 'Dr. Edward Miller', 'dr edward miller'),
    ('Where is the National FBLA-PBL Center located?', 'Reston, Virginia', 'reston virginia'),
    ('When was the Professional Division created?', '1989', '1989'),
    ('What is the national policy making body for FBLA-PBL, Inc.?', 'National Board of Directors', 'national board of directors'),
    ('What is the national publication for FBLA and FBLA-ML members?', 'Tomorrow''s Business Leader', 'tomorrows business leader'),
    ('What is the national publication for FBLA and FBLA-ML advisers?', 'Hotline', 'hotline'),
    ('What is the informational publication that each local chapter receives?', 'Chapter Management Handbook', 'chapter management handbook'),
    ('What is the national program that encourages chapters to team up to leverage their potential for success?', 'Connecting Chapters', 'connecting chapters'),
    ('What does CSA stand for?', 'Community Service Awards', 'community service awards'),
    ('What does BAA stand for?', 'Business Achievement Awards', 'business achievement awards'),
    ('What is the national program that recognizes local chapters who maintain or increase their membership over the previous year''s total?', 'Membership Achievement Award', 'membership achievement award'),
    ('Which officer presides over and conducts meetings according to Parliamentary Procedure?', 'President', 'president'),
    ('What is the written action plan called?', 'Program of Work', 'program of work'),
    ('Who is the president and CEO of FBLA-PBL?', 'Alexander T. Graham', 'alexander t graham'),
    ('In the officer installation ceremony, what color candle represents the reporter?', 'Violet', 'violet'),
    ('In the officer installation ceremony, what color candle represents the entire chapter?', 'White', 'white'),
    ('In the officer installation ceremony, what color candle represents the president?', 'Red', 'red'),
    ('In the officer installation ceremony, what color candle represents the vice president?', 'Orange', 'orange'),
    ('In the officer installation ceremony, what color candle represents the secretary?', 'Yellow', 'yellow'),
    ('In the officer installation ceremony, what color candle represents the treasurer?', 'Light Blue', 'blue'),
    ('In the officer installation ceremony, what color candle represents the historian?', 'Green', 'green'),
    ('In the officer installation ceremony, what color candle represents the parliamentarian?', 'Gray', 'gray'),
    ('Who is the Staff Accountant of FBLA-PBL?', 'Mary Ait', 'mary ait'),
    ('Who is the Sponsors & Partners Coordinator of FBLA-PBL?', 'Ashlee Woodson', 'ashlee woodson'),
    ('Who is the Customer Service Associate of FBLA-PBL?', 'Colin Murphy', 'colin murphy'),
    ('Who is the Membership Director of FBLA-PBL?', 'Lisa Smothers', 'lisa smothers'),
    ('Who is the Conference Manager of FBLA-PBL?', 'Robert Smothers', 'robert smothers'),
    ('Who is the Education Director of FBLA-PBL?', 'Kelly Scholl', 'kelly scholl'),
    ('Who is the Education Associate of FBLA-PBL?', 'Aric Mills', 'aric mills'),
    ('Who is the Director of Communications & Marketing of FBLA-PBL?', 'Gabrielle Gallagher', 'gabrielle gallagher'),
    ('Who is the Digital Marketing Coordinator of FBLA-PBL?', 'Lauren McMahon', 'lauren mcmahon'),
    ('Who is the FBLA National President?', 'Drew Lojewski', 'drew lojewski'),
    ('Who is the PBL National President?', 'Gabrielle Murphy', 'gabrielle murphy'),
    ('Who is the Professional Division National President?', 'Alan Rzepkowski', 'alan rzepkowsky'),
    ('Who is the FBLA National Secretary?', 'Hana Le', 'hana le'),
    ('Who is the FBLA National Treasurer?', 'John Lee', 'john lee'),
    ('Who is the FBLA National Parliamentarian?', 'Kianna Bolante', 'kianna bolante'),
    ('Who is the FBLA National Eastern Region Vice President?', 'Andrew Fox', 'andrew fox'),
    ('Who is the FBLA National Western Region Vice Presdient?', 'Sachin Sundar', 'sachin sundar'),
    ('Who is the FBLA National Southern Region Vice President?', 'Maria Manabat', 'maria manabat'),
    ('Who is the FBLA National North Central Region Vice President?', 'Rhea Mehta', 'rhea mehta'),
    ('Who is the FBLA National Mountain Plains Region Vice President?', 'Kaylee Reese', 'kaylee reese'),
    ('What year was the FBLA-ML division established at the national level?', '1994', '1994'),
    ('What state became the first state chapter?', 'Iowa', 'iowa');